Create de.lua
qbcore-framework/qb-ambulancejob pull request #125
Opened 2022-01-20 12:08 UTC by Seraph1982

2022-02-02 00:42 UTC, Tomboru requested changes
Just changed some weird translations.

They would make more sence in the context.

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        impossible = 'Aktion unmöglich...',
```suggestion
        impossible = 'Aktion kann nicht ausgeführt werden...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        no_firstaid = 'Du benötigst ein First Aid Kit',
```suggestion
        no_firstaid = 'Du benötigst ein Erste-Hilfe-Kasten',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        beds_taken = 'Betten sind belegt...',
```suggestion
        beds_taken = 'Die Betten sind belegt...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        possessions_taken = 'Alle deine Besitztümmer wurden genommen...',
```suggestion
        possessions_taken = 'Dir wurde alles abgenommen...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        revived = 'du hast eine Person wiederbelebt',
### 
```suggestion
        revived = 'Du hast eine Person wiederbelebt',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        wounds_healed = 'Deine Wunden wurden geheilt!',
```suggestion
        wounds_healed = 'Deine Wunden wurden verarztet!',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        civ_down = 'Zivilist Down',
```suggestion
        civ_down = 'Zivilist verletzt',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        self_death = 'Er selbst oder ein NPC',
```suggestion
        self_death = 'Sie selbst oder ein NPC',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        respawn_txt = 'Wiederbelebung in: ~r~%{deathtime}~s~ Sekunden',
```suggestion
        respawn_txt = 'RESPAWNE IN: ~r~%{deathtime}~s~ SEKUNDEN',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        respawn_revive = 'Halte [~r~E~s~] für %{holdtime} Sekunden um Wiederbelebt zu werden zu Preis von $~r~%{cost}~s~',
```suggestion
        respawn_revive = 'HALTE [~r~E~s~] FÜR %{holdtime} SEKUNDEN UM ZU RESPAWNEN FÜR $~r~%{cost}~s~',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        bleed_out = 'Du blutest aus in: ~r~%{time}~s~ Sekunden',
```suggestion
        bleed_out = 'DU BLUTEST AUS IN: ~r~%{time}~s~ SEKUNDEN',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        bleed_out_help = 'Du blutest aus in: ~r~%{time}~s~ Sekunden, dir kann geholfen werden',
```suggestion
        bleed_out_help = 'DU BLUTEST AUS IN: ~r~%{time}~s~ SEKUNDEN, DIR KANN GEHOLFEN WERDEN',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        request_help = 'Drücke [~r~G~s~] für eine hilfeanfrage',
```suggestion
        request_help = 'DRÜCKE [~r~G~s~] UM EIN SANITÄTER ZU RUFEN',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        help_requested = 'Rettungsdienst wurde verständigt',
```suggestion
        help_requested = 'SANITÄTER WURDEN BENACHRICHTIGT',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        healthy = 'Du bist wieder ganz gesund!',
```suggestion
        healthy = 'Du bist wieder völlig gesund!',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        mr = 'Herr.',
```suggestion
        mr = 'Herr',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        mrs = 'Frau.',
```suggestion
        mrs = 'Frau',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        dr_needed = 'Ein Doktor wird im Pillbox Krankenhaus benötigt',
```suggestion
        dr_needed = 'Ein Arzt wird im Pillbox Krankenhaus benötigt',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        revive_player = 'Belebe einen Spieler',
```suggestion
        revive_player = 'Spieler wiederbeleben',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        pain_level = 'Setzt dein oder eines Spielers schmerzlevel (Admin Only)',
```suggestion
        pain_level = 'Stellen Sie Ihre oder die Schmerzstufe eines Spielers (Admin Only)',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        heal_player_a = 'Keile einen Spieler oder dich selbst (Admin Only)',
```suggestion
        heal_player_a = 'Heile einen Spieler oder dich selbst (Admin Only)',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        message = 'Hallo %{gender} %{lastname}, <br /><br />Hiermit erhalten Sie eine Email über die Kosten ihres letzten Krankenhaus besuchs.<br />Die gesammt Kosten betragen: <strong>$%{costs}</str
```suggestion
        message = 'Hallo %{gender} %{lastname}, <br /><br />Hiermit erhalten Sie eine Email für die Kosten ihres letzten Krankenhaus Besuchs.<br />Die Gesamtkosten betragen: <strong>$%{costs}</strong><br /><br />Wir wünschen eine schnelle Genesung!'
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        close = '⬅ Schließe Menu',
```suggestion
        close = '⬅ Menü Schließen',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        pstash_button = '~g~E~w~ - Persönliches Fach',
```suggestion
        pstash_button = '~g~E~w~ - Persönliches Lager',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        pstash = 'Persönliches Fach',
```suggestion
        pstash = 'Persönliches Lager',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        armory_button = '~g~E~w~ - Waffenschrank',
```suggestion
        armory_button = '~g~E~w~ - Arsenal',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        armory = 'Waffenschrank',
```suggestion
        armory = 'Arsenal',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        storeveh_button = '~g~E~w~ - Verwahre Fahrzeug',
```suggestion
        storeveh_button = '~g~E~w~ - Fahrzeug einparken',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        storeheli_button = '~g~E~w~ - Verwahre Helikopter',
```suggestion
        storeheli_button = '~g~E~w~ - Helikopter einparken',
```

Even if its sounds weird, thats the official term

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        heli_button = '~g~E~w~ - Nimm einen Helikopter',
```suggestion
        heli_button = '~g~E~w~ - Helikopter ausparken',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        call_doc = '~g~E~w~ - Rufe Doktor',
```suggestion
        call_doc = '~g~E~w~ - Arzt rufen',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        ifaks = 'ifaks nehmen...',
```suggestion
        ifaks = 'Benutze Erste-Hilfe-Kasten...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        bandage = 'Verband benutzen...',
```suggestion
        bandage = 'Benutze Verband...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        painkillers = 'Schmerzmittel nehmen...',
```suggestion
        painkillers = 'Nehme Schmerzmittel...',
```

2022-02-02 00:42 UTC, Tomboru commented on locales/de.lua
> +        revive = 'Person wiederbeleben...',
```suggestion
        revive = 'Wiederbelebe Person...',
```

2022-02-11 06:59 UTC, FjamZoo commented
Please update the changes proposed.

2022-03-16 21:26 UTC, MikesModZ-Modding commented on locales/de.lua
> +        no_firstaid = 'Du benötigst ein First Aid Kit',
> 
**einen** Erste-Hilfe-Kasten

2022-03-16 21:49 UTC, MikesModZ-Modding commented on locales/de.lua
> +        revive = 'Person wiederbeleben...',
> 

Person reanimieren

2022-04-07 00:41 UTC, merged