Fix linting issues
qbcore-framework/qb-ambulancejob pull request #178
Opened 2022-05-07 16:34 UTC by TheiLLeniumStudios

**Describe Pull request**
Ignore the status checks. The errors will be gone once this is merged

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2022-05-12 10:06 UTC, IdrisDose commented
@TheiLLeniumStudios bump plz fix checks ;)

2022-05-13 06:20 UTC, TheiLLeniumStudios commented
@IdrisDose All checks are passing now

2022-05-15 01:19 UTC, BerkieBb requested changes

2022-05-15 01:19 UTC, BerkieBb commented on client/dead.lua
> +local function DrawTxt(x, y, width, height, scale, text, r, g, b, a, _)
Instead of makong it an underscore, just remove it

2022-05-15 01:19 UTC, BerkieBb commented on client/job.lua
> +    for k, _ in pairs(Config.Locations["roof"])do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on client/job.lua
> +    for k, _ in pairs(Config.Locations["main"])do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on client/main.lua
> +        for k, _ in pairs(Config.Locations["beds"]) do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on client/main.lua
> +    for k, _ in pairs(Config.Locations["beds"]) do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on client/main.lua
> +        for k, _ in pairs(CurrentDamageList) do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on server/main.lua
> +			for k, _ in pairs(PlayerInjuries[Player.PlayerData.source].limbs) do
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on server/main.lua
> +QBCore.Commands.Add("status", Lang:t('info.check_health'), {}, false, function(source, _)
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on server/main.lua
> +QBCore.Commands.Add("heal", Lang:t('info.heal_player'), {}, false, function(source, _)
You can remove this underscore completely

2022-05-15 01:19 UTC, BerkieBb commented on server/main.lua
> +QBCore.Commands.Add("revivep", Lang:t('info.revive_player'), {}, false, function(source, _)
You can remove this underscore completely

2022-05-15 05:44 UTC, merged